### ISSUE TITLE
No such file or directory: 'data/cifar10/train_images.npy'

### ISSUE THREAD

**Issue by zhangchuanyi96** [xiaoboxia/Classification-with-noisy-labels-by-importance-reweighting#1]
Traceback (most recent call last):
  File "main.py", line 62, in <module>
    train_data = data_load.cifar10_dataset(True, transform=transform_train(args.dataset), target_transform=transform_target,
  File "importance-reweighting/data_load.py", line 76, in __init__
    original_images = np.load('data/cifar10/train_images.npy')
  File "envs/pytorch/lib/python3.8/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data/cifar10/train_images.npy'

The example failed. Need help.

**Comment by xiaoboxia** [comment]
> Traceback (most recent call last):
> File "main.py", line 62, in 
> train_data = data_load.cifar10_dataset(True, transform=transform_train(args.dataset), target_transform=transform_target,
> File "importance-reweighting/data_load.py", line 76, in **init**
> original_images = np.load('data/cifar10/train_images.npy')
> File "envs/pytorch/lib/python3.8/site-packages/numpy/lib/npyio.py", line 428, in load
> fid = open(os_fspath(file), "rb")
> FileNotFoundError: [Errno 2] No such file or directory: 'data/cifar10/train_images.npy'
> 
> The example failed. Need help.

Hi, due to the size of datasets, you can find them in this link. https://drive.google.com/open?id=1Tz3W3JVYv2nu-mdM6x33KSnRIY1B7ygQ
